### ISSUE TITLE
timeframe seems to be ignored in the rule file

### ISSUE THREAD

**Issue by jesaremi** [Yelp/elastalert#1052]
i have a rule file (a basic frequency rule copied from the example) which has a timeframe of 10 days. When i run test-rule on it, it generates no hits however if I run test-rule with --days 10 it then generates what is expected:

```
timeframe:
  days: 10
```

This is an example of where the timeframe seems to be ignored:

```
D:\app\elastalert> elastalert-test-rule --config config.yaml  rules\frequency.yaml
...
elastalert_status - {'hits': 0, 'matches': 0, '@timestamp': datetime.datetime(2017, 4, 24, 19, 35, 59, 368000, tzinfo=tz
utc()), 'rule_name': 'SampleRule1', 'starttime': datetime.datetime(2017, 4, 23, 19, 35, 58, 290000, tzinfo=tzutc()), 'en
dtime': datetime.datetime(2017, 4, 24, 19, 35, 58, 290000, tzinfo=tzutc()), 'time_taken': 1.0469999313354492}
```

compare the above to the time I specify the days on the command line:

```
D:\app\elastalert>elastalert-test-rule --config config.yaml --days 10 rules\frequency.yaml
...
elastalert_status - {'hits': 56932, 'matches': 56932, '@timestamp': datetime.datetime(2017, 4, 24, 19, 42, 37, 761000, t
zinfo=tzutc()), 'rule_name': 'SampleRule1', 'starttime': datetime.datetime(2017, 4, 14, 19, 40, 52, 586000, tzinfo=tzutc
()), 'endtime': datetime.datetime(2017, 4, 24, 19, 40, 52, 586000, tzinfo=tzutc()), 'time_taken': 105.14399981498718}

```

**Comment by Qmando** [comment]
The timeframe is not related to the time each query covers. The timeframe is a sliding window of events that grows as time progresses. Elastalert will query at the current time and continue querying every few minutes. 

You can query it over the last 10 days of data using the --days flag, or with --start, as you've discovered, in order to test how it would have behaved had it been running that whole time.

With a timeframe of 10 days, you would leave elastalert running and when it hit num_events it would send an alert, if you passed 10 days, the old events would be removed and new ones added. It always tracks 10 days of the most recent events.
