### ISSUE TITLE
Multiple matches from a single rule query

### ISSUE THREAD

**Issue by mrchang7** [Yelp/elastalert#1070]
I'm trying flatline especially with threshold setting to 1, hoping to have an alert with no events for the query.  

By the way, with 0 hits it sometimes reports more than 1 matches and alerts (with a repeating pattern) .  I tried many different combinations of all the time-related settings; run_every, buffer_time, timeframe as well as data-arrival interval, but still cannot understand why it could generate multiple matches/alerts from 0 hits. 

My question is general. Can elastalert make multiple matches/alerts with a single query result (from a single rule execution), and how? 

Thanks.

**Comment by Qmando** [comment]
This is a known issue. Basically, it will sometimes split up a time period into two queries.
For example, run_every is 1 minute, but it tries to query 12:00 to 12:01:01, which is very slightly longer than a minute. Elastalert will then segment that into 1 minute pieces, with the second one consisting of only 1 second. Each query generates an alert because there are still no documents.

The default realert should prevent these extra matches from every being alerts.

**Comment by mrchang7** [comment]
Yeah we noticed the query window is slightly longer just like you mentioned. Okay fair enough. We will handle this in the enhancement. 

Thanks!

**Comment by Qmando** [comment]
This is on my list of things to fix.
