### ISSUE TITLE
Rule added to silence

### ISSUE THREAD

**Issue by warrior107** [Yelp/elastalert#1169]
Hi,
We are running to send alerts for any errors in our application. We have about 300 rules for different errors and are run in 10 minutes cycle.
Recently, it was observed that alerts were not sent only for a few rules, while they were sent for other errors. On further analysis, we observed that the rules were not even run in the cycle (there are no logs for these rules in console logs or elasticsearch). There were entires for the rules in **_type: silence** in elasticsearch index.
After modifying the last changed date for the rule files, elastalert picked the files and alert were sent as usual. There are no enhancements or realert setting being used.

Can you please help on this so we can ensure that this does not happen the future. These alerts are very crucial for functionality of the application

**Comment by Qmando** [comment]
If they were not run, it's because of one of two reasons:

1. There was an error when the rule was loaded. Since it successfully loaded after you modified it, this is probably not the case.

2. Some uncaught exception occurred while the alert code for one of these rules ran. In this case, you would have received a log message ``Uncaught exception running rule ...`` and an email if you set up ``notify_email`` and have SMTP settings.

I would closely monitor all documents of ``_type: elastalert_error`` (you can even set up a meta-elastalert to send you these), set up ``notify_email``, perhaps add ``disable_rules_on_error: false``

I'm pretty sure there would have SOME error message in the. Definitely use the ``--verbose`` if you are not already.

**Comment by warrior107** [comment]
i see a lot of errors in _type: elastalert_error. Will try with disable_rules_on_error: false.
thanks for helping
