### ISSUE TITLE
I don't seem to understand alert_on_new_data correctly...

### ISSUE THREAD

**Issue by Galendryl** [Yelp/elastalert#1277]
Hey guys,
I'm just here to ask for some guidance. Basically I have a ton of events that might occur in a normal timeframe (1 hour) in my syslog, and I want to only receive alerts like once per hour but no more than that since the error is a spamming one (one message every 30 sec). I was using Spike rule for my tests and it's working well so far except that I also want to be alerted when the very first message appears.

Like when the error starts triggering the Spike count, I want to be alerted right away and then once per hour at most. I tried using alert_on_new_data but it matched on some other messages that were in the field I specified so it didn't really work as I planned.

Can someone clarify this for me please?
Thanks for any help :)

G.

**Comment by Qmando** [comment]
alert_on_new_data only applies IF you are using query_key.

Normally, the entire timeframe (*2 for reference and current windows) must elapse AFTER the first instance of some new value of query_key for it to even consider alerting on it. I'll give an example

```
type: spike
timeframe:
  minutes: 10
spike_height: 5
threshold_cur: 10
query_key: hostname
```

Without alert_on_new_data, if some new hostname that hadn't been seen before appeared, it would wait at least 20 minutes before checking whether the second 10 minute window contained at least 10 events AND at least 5x more than the first 10 minutes.

With alert_on_new_data set to true, it would alert as soon as it saw 10 events within 10 minutes, because before that, the "reference window" has a count of 0, because that new hostname has never been seen before.

Adding
```
realert:
  hours: 1
``` 
will prvent you from getting more than 1 alert per hour per hostname.

**Comment by Qmando** [comment]
Basically, if some new value of query_key appears BUT is constant rate after that, it wont alert unless alert_on_new_data is set.

I'm not sure if this fits your use case, but it sounds like maybe you could just use
```
type: any
realert:
  hours: 1
query_key: foo
```
that way you'll get alerted on the first matching document for each unique query_key, and then not again for another hour for that unique value.

**Comment by Galendryl** [comment]
Hello,
Yes you're defenitely right. I'll use "realert" instead, I absolutely didn't see it in the doc for some reason although I've been searching for an otpion like that for days.

Thanks for helping me out.
