### ISSUE TITLE
Using Elasticsearch Aggregations with Elastalert

### ISSUE THREAD

**Issue by stephanbuys** [Yelp/elastalert#145]
Hi there,

Is there any support for the use of aggregations (https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-aggregations.html) in Elastalert? The kind of alert that this could support would be a change in the 'count' of different terms in a 'hostname' field, for example.

-S

**Comment by Qmando** [comment]
You can, although it only supports terms aggregations now, and only for specific rule types. To use this you will need to set ``use_count_query: true`` and ``query_key: hostname``. This will return counts for each value of hostname, which can then be used with spike, frequency or flatline rule. It sounds like you might want to try it with spike rule, which would allow you to alert if the count for any given hostname went up or down from it's normal rate.

**Comment by stephanbuys** [comment]
@Qmando thanks for the pointer, could you point me to the relevant part of the code, perhaps we can contribute some contributions? Quick question, can we use the count aggregation on the change alert type? I'm interested in knowing whenever the count changes of the number of hosts reporting.

**Comment by Qmando** [comment]
Contributions are definitely welcome!

Here's where the query is generated: https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L185

The query is run here: https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L269

and it can be used with rules which implement add_terms_data: https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L74.

You can perhaps use the "new_terms" rule if you wish to monitor the number of unique hosts, which would alert when a new hostname appears. The change rule does not work because it looks at a specific field from Elasticsearch chaning between two subsequent documents, not the total number of documents or total number of unique values.

**Comment by stephanbuys** [comment]
@Qmando thanks again, rereading spike's different modes I'm thinking that I can do 'spike_type: both' and 'spike_height: 1', but I'll experiment.

**Comment by Qmando** [comment]
That should be essentially what you want. Keep in mind that ``timeframe`` must be set with care such that the "reference" and "current" windows will always contain the same number of logs. When using aggregation queries, the resolution for the timestamp is only as high as the ``run_every`` setting.

**Comment by Qmando** [comment]
Original problem could now be solved with cardinality rule type. Added in #200.

In the future, I would like to see more support for custom aggregations.
