### ISSUE TITLE
Using threading for to avoid blocking on ES queries

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#17]
Rewrite the rules loop to use Python threading facilities, allowing rules to be run in parallel in multicore environments. Inspect the performance implications of this and correct for any lock contention or global state issues that may arise.

**Comment by jayeshdhamechai** [comment]
Async execution of rules would be great and helpful. Can this be achieved soon or there are other features/bugs with more priority?

**Comment by tanyewei** [comment]
waiting...

**Comment by zhiaixuexi** [comment]
hi @Qmando ,
is elastalert support on multi thread now, or plans to be?

**Comment by bananabr** [comment]
I want to work on this, but could figure out my way around the rule processing flow to lock shared resources properly. If the maintainer could help on this, I would be glad get this working.

**Comment by lucasrodcosta** [comment]
Hi everyone.

Few weeks ago I took a look on the code to start work on this feature.
But I realized that to control the shared resources properly (as mentioned by @bananabr) is a bit complicated.

However, I guess that exists an another good approach and I would like to see the @Qmando opinion about it.  
Instead of change the core of `ElastAlerter` class to introduce the ability of his unique instance handle shared resources, my approach consists in create multiple `ElastAlerter` instances.  
Some like this:

```python
import multiprocessing

# ...

def start_client(worker_id):
    client = ElastAlerter(args, worker_id=worker_id)
    client.start()

def main(args=None):
    num_workers = multiprocessing.cpu_count()
    pool = multiprocessing.Pool(num_workers)
    pool.map(start_client, range(0, num_workers))
```

PS: I omitted a lot of important stuff in the code above for simplicity.  
I think that this approach can facilitate the development and improve the performance making use of the multiple processor cores.

What do you guys think?
