### ISSUE TITLE
Q: Can we set global rule config options?

### ISSUE THREAD

**Issue by naseemkullah** [Yelp/elastalert#2111]
Such as `kibana_url`, instead of setting it in every rule? 

TIA

**Comment by naseemkullah** [comment]
I suppose if they are set in `/opt/config` ?

**Comment by thommor** [comment]
Yes you can.

Just place it in your config.yaml

**Comment by thommor** [comment]
The reason you get this error is because the rule is ran against a validator before the options from the config are copied into the rule. This means you will get this error for any option that is required `required_locals = frozenset(['alert', 'type', 'name', 'index'])`.

To get around this you would have to check if one of there required locals is in the global config and copy it to the rule before it is passed to the validator but you would have to ask @Qmando whether that would be accepted as a PR


The rule is passed to the validator [here](https://github.com/Yelp/elastalert/blob/5fe946b3877f4a25feb0c46f609b6125cc87f444/elastalert/config.py#L182)
The global config options are copied to the rule [here](https://github.com/Yelp/elastalert/blob/5fe946b3877f4a25feb0c46f609b6125cc87f444/elastalert/config.py#L215)

**Comment by naseemkullah** [comment]
Thanks for the explanation @thommor .

So if I understand correctly, we can apply global options in our `config.yaml` that will be propagated to all rules such except for the `required_locals` mentioned.

I think that would suffice for the time being, however if you and/or @Qmando see value in being able to define any of the `required_locals` globally, I can take a stab at it, especially since you've showed which are the files in question.

**Comment by naseemkullah** [comment]
PS @thommor  I've created a PR for the helm chart regarding this ability to add global rule options in the `config.yaml`, if you have a moment feel free to have a look and chime in!

https://github.com/helm/charts/pull/11160/files

**Comment by thommor** [comment]
Looks fine to me

**Comment by naseemkullah** [comment]
Thanks!
Closing this issue.
