### ISSUE TITLE
Alerts for different rules are aggregated together

### ISSUE THREAD

**Issue by gopalganu** [Yelp/elastalert#228]
I have seen twice that alerts from two different rules were put into a single email.
The only reason as per my understanding is that _id returned for aggregates is an incorrect one and which causes alerts to be linked to wrong rule.

Has anyone else seen this happening? Any idea what can be the reason.

**Comment by Qmando** [comment]
This has happened before, because the aggregate_id field was an analyzed string which would cause a query for "d-Gj4ld8E" match something like "K5jndp4-d". This was fixed in https://github.com/Yelp/elastalert/commit/f843bcc5100073c8d087c3d2c42fc61423477426 two months ago. If you pull the latest version, you can run ``elastalert-create-index`` and choose the old index to copy, and it should update the mapping.

**Comment by gopalganu** [comment]
Thanks! Excellent.

**Comment by gopalganu** [comment]
Hello

Regarding the elastalert-create-index, do you mean to say that we need to create index by a new name? Didn't quite get what is the correct way to move from older version to 0.0.56, if mappings are changing. The create-index gives excepts that index already exist. Whats steps do you suggest

**Comment by Qmando** [comment]
You cannot change the mapping once documents have been added, so you can either:
1. Delete the original index and create a new one
2. Create a new index with a different name, copying the documents from the first. You can then delete the first and optionally add an alias to the new one so it has the same name.

**Comment by gopalganu** [comment]
Thanks for the info.
