### ISSUE TITLE
how to recover my ELK

### ISSUE THREAD

**Issue by DanielHuZM** [Yelp/elastalert#2367]
I use **elastalert-create-index** to create a writeback index in es. It works no matter on my computer and testing environment. However, it rushed my ELK on formal environment. The **ONLY** one difference between testing and formal environment is that there are multiple sets of accounts , and each of which corresponds to an independent index on formal environment. After I USE **elastalert-create-index**, all indexs disappeared, all accounts showed unauthorized and one plugin of ELK was down. 

I want to know why it happened and how could I do in the future.
Please help me, thank you very much.

**Comment by Theoooooo** [comment]
If all your indexes dissapear and you don't have any snapshot repository, you can't do much about it ...
I also got multiples accounts on both my testing and production environment and never encounter this kind of issue. I used a superuser account for the create of the index with elastalert-create-index.
You can check your ES logs but i don't think you will found many informations because it's mostly cluster state informations

**Comment by Theoooooo** [comment]
Also the first time you setup the default service account for ES, it generate random passwords according on how you generate these passwords (account elastic, kibana, beats_system, ...)
If you can find the password for the kibana account you could be able to access kibana again

**Comment by DanielHuZM** [comment]
I have checked my ES logs , they are still alive. I used a normal account for the create writeback index, all accounts showed unauthorized at the same time. I guess some problems happened in the tenant of Kibana.

**Comment by Theoooooo** [comment]
I didn't check but maybe you can recover the password for the default service account elastic. That's sound the best solution for me but i never try it out
