### ISSUE TITLE
custom date format

### ISSUE THREAD

**Issue by villain** [Yelp/elastalert#443]
i've had a read through the docs and couldnt find anything, but i was wondering if its possible to use a custom date format somewhere in the configuration. the mapping for my date field is defined as 'date_hour_minute_second', and when running elastalert-test-rule i get an error:

ElasticsearchParseException[failed to parse date field [2016-03-23T09:22:47.536136Z], tried both date format [date_hour_minute_second], and timestamp number]; nested: IllegalArgumentException[Invalid format: "2016-03-23T09:22:47.536136Z" is malformed at ".536136Z"]; }

**Comment by Qmando** [comment]
The only formats officially supported right now are ISO8601 (2016-03-23T09:22:47Z), Unix (1458838790) and Unix time in MS (1458838790000). I think it's possible for other formats, as long as they are indexed in Elasticsearch as a date/time type and can be parsed by the dateutil Python library.

**Comment by unicell** [comment]
I also hit the same issue, because the ES index was using customized date format in mappings[1]. I sent out a pull request to allow using `custom` timestamp_type and provide `timestamp_format` along with it.

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html
