### ISSUE TITLE
spike alert fails using use_terms_query and query_key

### ISSUE THREAD

**Issue by tlamay** [Yelp/elastalert#484]

**Comment by tlamay** [comment]
name: Spike - RecordType Aggregate
index: logstash-%Y.%m.%d
use_strftime_index: true
alert:
- "email"
email:
- "foo@bar.com"

filter:
- query:
    query_string:
      query: "recordType: *"

type: spike
query_key: recordType.raw
spike_height: 2
spike_type: "both"

timeframe:
  seconds: 1

threshold_ref: 20

use_terms_query: true
doc_type: logs

**Comment by Qmando** [comment]
What do you mean specifically by fail?

**Comment by tlamay** [comment]
If I disable use_terms_query, this alert works as expected. When I enable the use_terms_query, I get 'hits' relating to each aggregation (counts per query_key) and the elasticsearch query and results look fine. But alerts are never triggered per key, even with realert: 0. 

INFO:elastalert:Ran Spike - RecordType Aggregate from 2016-04-19 15:33 EDT to 2016-04-19 15:33 EDT: 8 query hits, 0 matches, 0 alerts sent

Without use_terms:

INFO:elastalert:Ran Spike - RecordType AggregateZZZZ from 2016-04-19 15:54 EDT to 2016-04-19 15:54 EDT: 266 query hits, 5 matches, 5 alerts sent

**Comment by Qmando** [comment]
Ah, I think the problem is the timeframe. Using ``use_terms_query`` reduces the time resolution and if it's longer than 2 seconds, it won't work with such a small timeframe.

**Comment by tlamay** [comment]
I had chosen the small timeframe in order to aid debugging. I've just tried it with 60 seconds and it still never alerts. My ideal timeframe would be 5m. I will try that again, but it hadn't originally worked.

**Comment by Qmando** [comment]
It won't ever alert after a single query because in a single query, all the events are lumped together into a single timestamp.

**Comment by tlamay** [comment]
The query is run every 5 minutes. Do you mean to say that it should work after the subsequent runs? Because it doesn't. If you mean something else, can you describe a work around?

**Comment by Qmando** [comment]
If ``run_every`` is 5 minutes, that means that the resolution of events is 5 minutes. If your timeframe is 1 minute, it can't compare adjacent minutes to each other. The timeframe has to be larger than ``run_every`` if you are using ``use_terms_query``

**Comment by tlamay** [comment]
I guess I'm misunderstanding some fundamental relationships between run_every, timeframe, and perhaps buffer_time in other cases.

I've set run_every to 1 minute. I've set threshold to 3 minutes. When querying, it's always looking at a range of 1 minute:

"range": {
                "@timestamp": {
                  "gt": "2016-04-19T22:44:15Z",
                  "lte": "2016-04-19T22:45:15Z"
                }
              }

Timeframe suggests that it will create a count over a window of 3 minutes. But the query isn't indicative of a 3m average, unless there's aggregation of windows happening in the elastalert index itself?

The reason I'd like to use terms_query is that I can easily have more than 10K events in > 5minutes of window.

1 minute run_every is tight but works for now.

Semi-unrelated, does buffer_time always need to be greater than timeframe as well?

**Comment by Qmando** [comment]
So when you have ``use_terms_query`` set, with run_every set to 1 minute, a single query will run every minute and all of the different documents in that minute will be counted. If there are 5 documents for "foo" and 10 for "bar" within that minute, this will essentially be stored internally as {"timestamp": <end of query range>, "value": "foo", "count": 5}. Without ``use_terms_query``, you get 5 individual documents with perfectly accurate timestamps all with count 1. Internally, these are all treated the same.

Sure, this might represent an "average" over than 1 minute, but it's treated as if it's 5 events all occurring at the same time. The spike rule will compare the counts of documents in two adjacent sliding windows, each of width timeframe. So if timeframe is 1 minute, it's only look at 2 minutes worth of documents at any given time. If run_every is bigger than this, say 5 minutes, that means that you will never have documents in both adjacent windows at the same time, because they only occur 5 minutes.

Without use_terms_query, each query is overlapping. The default buffer_time of 45 minutes means that each query will cover 45 minutes, with just run_every determining how much overlap there is. ElastAlert will then de-duplicate all the documents. This is so that if you upload a document that's timestamp is 5 minutes in the past, say if some part of your infrastructure lagged for a minute, then it would still be counted. The timeframe will always be a sliding window relative to the most recent document, so it doesn't really matter what buffer_time is. Timeframe could be a week and it would just keep up to a weeks worth of documents in memory at all times.

The one requirement for buffer_time is that it needs to be more than run_every. Otherwise, for example, if query the last 30 seconds of data, and then wait a minute, then do the same, but you would be missing 30 seconds.
