### ISSUE TITLE
Flatline to check the total number of events is above a given threshold

### ISSUE THREAD

**Issue by sunrise-son** [Yelp/elastalert#495]
Hi,
I'm going to use ElastAlert in my project and I'm exploring rule types. What confuses is the Flatline concept. I would like to use this rule both for alerting if the events number goes above and under a threshold. Why can I use it only with the "under" case?

**Comment by Qmando** [comment]
For above, use frequency. They are basically the same, except flatline is for under a threshold and frequency is for over.

**Comment by sunrise-son** [comment]
The way those rules work is slightly different. I am familiar with Frequency and when setting realert=0 on its instance causes sending multiple alerts, although I expect only one - the threshold has been exceeded.

I have a proposition for the Flatline rule: if the threshold value is negative, the rule converts it to positive and check if the events count is over it. I can prepare a pull request.
If you consider this principle as ugly an ugly one, please, provide me prettier and I'll code it.

**Comment by Qmando** [comment]
That seems like it should be a flag on the frequency alert instead of a negative threshold. It works that way now because when it hits num_events, it sends an alert and then resets its counter. If it immediately encounters num_events again, it will alert again. 

I could see there being a flag that if doesn't reset its counter but only will alert again if it dips below the threshold then back above it.
