### ISSUE TITLE
Is end time exclusive for Spike alert?

### ISSUE THREAD

**Issue by yuan0122** [Yelp/elastalert#555]
Hi, is "end" timestamp exclusive for Spike alert? 

If I run the following elastalert with type of Spike, and timeframe = 1hour
`elastalert --config /etc/elasticsearch/elastalert.yml --rule my_rule.yaml --start 2016-05-30T00:00:00 --end 2016-05-30T02:00:00`

I didn't get any match.

But if I change the end time to `2016-05-30T02:01:00` I will get a match since there are several hits right on 2016-05-30T02:00:00. So I'm wondering if the end time is exclusive.

Thanks!

**Comment by Qmando** [comment]
The query itself IS inclusive of the endtime (https://github.com/Yelp/elastalert/blob/master/elastalert/elastalert.py#L220)

For the spike rule, it looks like it is exclusive (https://github.com/Yelp/elastalert/blob/master/elastalert/ruletypes.py#L371)

Basically, the time between the first event and the one that might trigger an alert must be greater than 2x the timeframe. The first event "resets" after each alert. There are some other exceptions, like if you are using query_key + alert_on_new_data.

I'm not sure if there is any reason for it to be exclusive and not inclusive. I think have the comparison be <= instead of < would be ok.

**Comment by yuan0122** [comment]
Thank you for your answer!
