### ISSUE TITLE
Elastalert Test Script doesn't work with --data option

### ISSUE THREAD

**Issue by AwesomeJohnR** [Yelp/elastalert#575]
The --data option reads json in with a different structure than when querying elastic directly.

When querying from elastic, the json is in the form of:
`{u'count': 1, '_type': u'log', u'fields': None, u'tags': [u'release'], u'beat': {u'hostname': u'<hostname>', u'name': u'<name>'}, u'input_type': u'log', u'@timestamp': '2016-06-13T15:56:37.897Z', '_index': u'filebeat-sdm-2016.06.13', u'source': u'/var/log/messages', u'offset': 331582, u'message': u'Jun 13 09:07:01 ...message data', '_id': u'AVVKesOqw_PHbqjJAMSO', u'type': u'log'}`

When reading the same data in via the --data option, the json is in the form of:
`{'_id': 'AVVKesOqw_PHbqjJAMSO', '_source': {'count': 1, 'fields': None, 'tags': ['release'], 'beat': {'hostname': '<hostname>', 'name': '<name>'}, 'input_type': 'log', '@timestamp': datetime.datetime(2016, 6, 13, 15, 56, 37, 897000, tzinfo=tzlocal()), 'source': '/var/log/messages', 'offset': 331582, 'message': 'Jun 13 09:07:01...message data', '_id': 'AVVKesOqw_PHbqjJAMSO', 'type': 'log'}}`

The error received was:

```
ERROR:root:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 903, in alert
    return self.send_alert(matches, rule, alert_time=alert_time)
  File "/usr/lib/python2.7/site-packages/elastalert/elastalert.py", line 964, in send_alert
    alerter.alert(matches)
  File "/usr/lib/python2.7/site-packages/elastalert/alerts.py", line 226, in alert
    elastalert_logger.info('Alert for %s at %s:' % (self.rule['name'], match[self.rule['timestamp_field']]))
KeyError: '@timestamp'

ERROR:root:Uncaught exception running rule Landing Zone API Not Available: '@timestamp'
```

**Comment by Qmando** [comment]
It should probably be more flexible, but right now it accepts the document's _source. You can add multiple documents by putting them into an array. Keep in mind that this method does not test your filters, everything in the data is assumed to already match.

**Comment by AwesomeJohnR** [comment]
I'm not sure you get my meaning.  I did not include _source or _id in my json format.  Those were put in there via the json parser used in the python script.  In my mind, I should be able to read from elastalert with the --save-json flag and get an output json file.  That works just fine but when I then use that file as an input via the --data flag, it fails with the above error.

**Comment by Qmando** [comment]
I see! Yes, this is a problem.

The --data flag replaces all of the Elasticsearch functionality with crude "mock" functions. In this case, it calls process_hits which is supposed to get rid of _source and flatten _id and _type into it, https://github.com/Yelp/elastalert/blob/master/elastalert/test_rule.py#L150. 

However, https://github.com/Yelp/elastalert/pull/364/files changed process_hits to actually return a new list instead of modifying them in place, but test_rule.py didn't get updated.

Thanks for noticing this. It should be a pretty simple fix. Although, there are likely other inconsistencies with the "mock" functions in test_rule.py. There's just a bunch of issues with that file anyway actually...

**Comment by AwesomeJohnR** [comment]
Any idea when this will get a fix @Qmando or maybe one is already in progress that I'm missing?
