### ISSUE TITLE
is_silenced causes error on new index

### ISSUE THREAD

**Issue by Qmando** [Yelp/elastalert#61]
create_index only creates a mapping for the silence type for rule_name. When is_silenced tries to query it sorts by "until" which doesn't yet exist in the index. The mapping should be specified for every type.

**Comment by gopalganu** [comment]
I am using version 0.0.44 and get the following error.
This is a frequency rule. What may be the reason.


elastalert_status/silence/_search?_source_include=until%2Cexponent&size=1 [status:400 request:0.005s]
ERROR:root:Error while querying for alert silence status: TransportError(400, u'SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[G4zGZ6nPSwaOPw_1KoF9Iw][elastalert_status][0]: SearchParseException[[elastalert_status][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"filter": {"term": {"rule_name": "instrumentation-errors.56E77923-D99D-4962-88CC-04DDE460EB18"}}, "sort": {"until": {"order": "desc"}}}]]]; nested: SearchParseException[[elastalert_status][0]: from[-1],size[-1]: Parse Failure [No mapping found for [until] in order to sort on]]; }]')

**Comment by Qmando** [comment]
@gopalganu Did run create_index.py? It should upload a mapping to the elastalert_status which will prevent this error.

**Comment by gopalganu** [comment]
I didn't run it manually, do I have to?
