### ISSUE TITLE
use_count_query changes rule behavior 

### ISSUE THREAD

**Issue by rmartin8** [Yelp/elastalert#771]
Here is my rule:

es_host: ********
es_port: 9200
name: Warnning_Elasticsearch
type: frequency
index: logstash-*
num_events: 5
timeframe:
  hours: 1
use_count_query: true
filter:
- term:
    level: "warn"

alert:
- "email"

email:
- "*****"

And in the config file:

run_every:
  minutes: 1
buffer_time:
  days: 1
es_host: *******
es_port: 9200
highlight=send_get_body_as#transport
writeback_index: prueba
realert:
  minutes: 0
alert_time_limit:
  days: 1
smtp_host: **********
smtp_port: ***
from_addr: **********

I hope that the alert start one day ago, run every minutes and use intervals of one hour, to compare the numbers of docs in the query with the num_events, but the alert look for docs in 1 minute intervals, every 1 minute. This behavior is only viewed when use_count_query is set.

**Comment by Qmando** [comment]
Whether you use use_count_query or not, all the events are added to a 1 hour sliding time window. You will still only get an alert if num_events documents occur within an hour of each other. Is that not the expected behavior?

 You expect a query to be made that covers an entire hour every minute? If the window's overlap, how would we know exactly how many documents there are?
