### ISSUE TITLE
bosun.org

### ISSUE THREAD

**Issue by Asimov4** [Yelp/elastalert#85]
Hi!

Have you considered integration with https://bosun.org/?

It looks like Bosun supports setting up alerts against Elasticsearch too.

**Comment by bechtoldt** [comment]
@Asimov4 how would a reasonable integration look like?

**Comment by Asimov4** [comment]
Maybe to clarify my question: did you consider using bosun.org before starting the elastalert project? And if you did, what made you decide to write elastalert?

I am trying to figure out whether to test the more mature/more complex project (bosun) first or the newer simpler project (elastalert).

**Comment by ivanlei** [comment]
@Asimov4 We did not find/consider bosun.org before writing ElastAlert. We're not well informed to make a comparison.

**Comment by Qmando** [comment]
At the time I started ElastAlert, I had not looked into Bosun. Having looked into it since, while ElastAlert does not offer as many features, a nice interface, and still contains some issues, it still serves some use cases better. 

 We already had several Elasticsearch clusters, used by various teams, who needed a quick way to setup basic alerting for various metrics and hook up custom Python code. ElastAlert lets use set up new alerts extremely fast by making basic filters or copying them from existing Kibana dashboards and setting a few basic options. ElastAlert is also very lightweight compared to Bosun and doesn't required copying data through scollector from Elasticsearch.

**Comment by Asimov4** [comment]
Thanks a lot! That is really helpful.
